identifier_name:
    min_length:
        warning: 0
    max_length:
        warning: 40
        error: 50

disabled_rules:
- trailing_whitespace
- line_length
- vertical_whitespace
- unused_optional_binding
- force_cast
- identifier_name
- function_body_length

excluded:
- Pods
- Weekand/AppDelegate.swift
- Weekand/SceneDelegate.swift

included:
- Weekand
